### ISSUE TITLE
Nunca crear un solo repo para todas las tareas

### ISSUE THREAD

**Issue by yosbel-penate** [AleSGXRD/Manejo-de-Excepciones#1]
cada proyecto debe tener su repo, y se debe llamar con un nombre que informe sobre lo que tiene y nunca decir tarea

**Comment by yosbel-penate** [comment]
nunca poner varios proyectos dentro de un mismo repo, si no el que quiera uno debra descargar todo

**Comment by AleSGXRD** [comment]
profe ya reviseme la tarea

**Comment by yosbel-penate** [comment]
No subiste el código, subiste los archivos compilados. Además el nombre debe dar a conocer el tipo de error ejemplo que entiendes por usuarioexcepción? Es que no existe, o no tiene correo ?

**Comment by AleSGXRD** [comment]
Q alguno de los datos es incorrecto(nombre o contraseña), y después heredan de el los errores de q la celda del nombre no tenga ningún valor, y otro para la contraseña

**Comment by yosbel-penate** [comment]
Las excepciones que lanzan son específicas de un dominio para poder luego atraparlas cuando son lanzadas

**Comment by AleSGXRD** [comment]
Mire a ver ahora, están sin compilar y más entendibles

**Comment by yosbel-penate** [comment]
Mejor tiemes 5 ponme una issue para quitar tu nombre de esta tarea, te faltan 2 mas

**Comment by yosbel-penate** [comment]
Su evaluación es 5 faltan 2 tareas, ponfame una issue para quitar su nombre de esta
